service: aws-shop-site

frameworkVersion: '3'

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs14.x


plugins:
  - serverless-finch

custom:
  client:
    bucketName: shop-site-bucket
    distributionFolder: build
    indexDocument: index.html
    errorDocument: index.html
